USE AMAZON 

/* DDL OPERATIONS */

CREATE TABLE EMPLOYESS_DATA (EMPID INT,EMPNAME CHAR(10),EMPAGE TINYINT)

/* ALTER */
ALTER TABLE EMPLOYESS_DATA ALTER COLUMN EMPNAME VARCHAR(10)

ALTER TABLE EMPLOYESS_DATA ADD EMPSALARY MONEY 

ALTER TABLE EMPLOYESS_DATA DROP COLUMN EMPID 

/* SP_RENAME */
SP_RENAME 'EMPLOYESS_DATA.EMPSALARY','EMPTAX'


/* TO SEE THE TABLE */

SELECT *FROM EMPLOYESS_DATA

SELECT EMPNAME,EMPAGE FROM EMPLOYESS_DATA


/* INSERT */
INSERT INTO EMPLOYESS_DATA VALUES ('JOHN',27,120)
INSERT INTO EMPLOYESS_DATA VALUES ('PETER',30,140)
INSERT INTO EMPLOYESS_DATA VALUES ('STEVE',32,160)
INSERT INTO EMPLOYESS_DATA VALUES ('BRAD',20,180)
INSERT INTO EMPLOYESS_DATA VALUES ('SMITH',18,190)

INSERT INTO EMPLOYESS_DATA VALUES ('KIRAN',12,90),('SRINU',11,80),('LAYYA',10,70)

/* UPDATE */

UPDATE EMPLOYESS_DATA SET EMPTAX=380 WHERE EMPNAME='JOHN'

UPDATE EMPLOYESS_DATA SET EMPAGE=40 WHERE EMPNAME='KIRAN'

/* DELETE */

DELETE EMPLOYESS_DATA WHERE EMPNAME='BRAD'

DELETE EMPLOYESS_DATA

/* TRUNCATE */
TRUNCATE TABLE EMPLOYESS_DATA

SELECT *FROM EMPLOYESS_DATA

/* DROP */
DROP TABLE EMPLOYESS_DATA

/* CHANGE TABLE NAME */
EXEC sp_rename 'dbo.EMPLOYESS_DATA', 'STUDENTS_DATA'

